# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Tempus Musicum
tagline:          'publishing projects for early and traditional music'
description:      'To be added'
url:              http://tempusmusicum.net
baseurl:          /tempus-musicum

author:
  name:           'Francis Sim'
  url:            http://simdesign.de

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com//scotusnotes/tempus-musicum
